Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bakers.Data;
using Bakers.Models;
using Bakers.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Bakers.Models.ViewModels;
using System.Security.Claims;

namespace Bakers.Controllers
{
    public class OrdersController : Controller
    {
        private readonly BakersDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public OrdersController(BakersDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }
        [Authorize(Roles = "admin")]
        // GET: Orders
        public async Task<IActionResult> Index(string searchField = " ")
        {
            return View(await _context.Order
                  .Where(o => !o.IsHidden)
                  .Include(o => o.Products)
                  .Include(o => o.User)
                  .ToListAsync());
        }

        [Authorize(Roles = "admin")]
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Products)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [Authorize(Roles = "admin")]
        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["Products"] = new SelectList(_context.Set<Product>(), "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "FirstName");
            return View();
        }

        [Authorize(Roles = "admin")]
        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OrderDate,Street,Zip,City,ProductIds,UserId")] Order order)
        {
            if (order.ProductIds == null)
            {
                order.ProductIds = new List<int>();
            }

            if (ModelState.IsValid)
            {
                order.Products = new List<Product>();
                foreach (int id in order.ProductIds)
                {
                    order.Products.Add(_context.Product.FirstOrDefault(p => p.Id == id));
                }

                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        [Authorize(Roles = "admin")]
        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }            

            ViewData["Products"] = new SelectList(_context.Set<Product>().Where(p => p.Favorite == true), "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "FirstName", order.UserId);
            return View(order);
        }

        [Authorize(Roles = "admin")]
        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrderDate,Street,Zip,City,ProductIds,UserId,Delivered")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (order.ProductIds == null)
            {
                order.ProductIds = new List<int>();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Order existingOrder = _context.Order.Include(o => o.Products).First(o => o.Id == id);
                    existingOrder.OrderDate = order.OrderDate;
                    existingOrder.Street = order.Street;
                    existingOrder.Zip = order.Zip;
                    existingOrder.City = order.City;
                    existingOrder.IsHidden = order.IsHidden;
                    existingOrder.UserId = order.UserId;
                    existingOrder.Delivered = order.Delivered;
                    existingOrder.Products.Clear();

                    
                    foreach (int productIds in order.ProductIds)
                    {
                        existingOrder.Products.Add(_context.Product.FirstOrDefault(p => p.Id == productIds));
                    }
                    _context.Update(existingOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "FirstName", order.UserId);
            return View(order);
        }

        [Authorize(Roles = "admin")]
        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Products)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [Authorize(Roles = "admin")]
        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
            }
            var order = await _context.Order.FindAsync(id);
            order.IsHidden = true;
            //if (order != null)
            //{
            //    _context.Order.Remove(order);
            //}
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return _context.Order.Any(e => e.Id == id);
        }

        [Authorize(Roles = "admin, user, employee")]
        public async Task<IActionResult> MyOrders()
        {
            var currentUser = _httpContextAccessor.HttpContext.User;
            var userIdClaim = currentUser.FindFirst(ClaimTypes.NameIdentifier);
            string userId = "";

            if (userIdClaim != null)
            {
                userId = userIdClaim.Value;
            }

            var orders = await _context.Order
                .Where(o => !o.IsHidden && o.UserId == userId)
                .Include(o => o.Products)
                .Include(o => o.User)
                .ToListAsync();

            if (orders.Count > 0)
            {
                return View(await _context.Order
                    .Where(o => !o.IsHidden && o.UserId == userId)
                    .Include(o => o.Products)
                    .Include(o => o.User)
                    .ToListAsync());
            } else
            {
                ViewData["NoOrders"] = "Client has no orders.";
                return View();
            }
        }
    }
}

Controllers/VarietiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bakers.Data;
using Bakers.Models;
using Bakers.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Bakers.Models.ViewModels;
using System.Runtime.Intrinsics.Arm;

namespace Bakers.Controllers
{
    public class VarietiesController : Controller
    {
        private readonly BakersDbContext _context;

        public VarietiesController(BakersDbContext context)
        {
            _context = context;
        }

        // GET: Varieties
        public async Task<IActionResult> Index(string searchField = "")
        {
            List<Variety> varieties = await _context.Variety
                .Where(v => !v.IsHidden)
                .Include(v => v.Products)
                .ToListAsync();

            if (!string.IsNullOrEmpty(searchField))
                varieties = varieties.Where(v => v.Name.Contains(searchField) && !v.IsHidden).ToList();

            if (!varieties.Any())
            {
                ViewData["NoProducts"] = "No products found.";
            }

            ViewData["searchField"] = searchField;
            return View(varieties);

        }

        // GET: Varieties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Variety == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety
                .Include(p => p.Products)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (variety == null)
            {
                return NotFound();
            }

            return View(variety);
        }

        [Authorize(Roles = "admin")]
        // GET: Varieties/Create
        public IActionResult Create()
        {
            ViewData["Products"] = new SelectList(_context.Set<Product>(), "Id", "Name");
            return View();
        }

        [Authorize(Roles = "admin")]
        // POST: Varieties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ProductIds")] Variety variety)
        {
            if (ModelState.IsValid)
            {
                variety.Products = new List<Product>();
                foreach (int id in variety.ProductIds)
                {
                    variety.Products.Add(_context.Product.FirstOrDefault(p => p.Id == id));
                }

                _context.Add(variety);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(variety);
        }
        [Authorize(Roles = "admin")]
        // GET: Varieties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Variety == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety.FindAsync(id);
            if (variety == null)
            {
                return NotFound();
            }

            List<Product> products = _context.Product.Where(p => p.VarietyId == variety.Id).ToList();

            ViewData["Products"] = new MultiSelectList(_context.Set<Product>(), "Id", "Name", products.Select(p => p.Id));
            return View(variety);
        }

        // POST: Varieties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ProductIds")] Variety variety)
        {
            if (id != variety.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    variety.Products = new List<Product>();
                    foreach (int productId in variety.ProductIds)
                    {
                        variety.Products.Add(_context.Product.FirstOrDefault(p => p.Id == productId));
                    }

                    _context.Update(variety);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VarietyExists(variety.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Products"] = new SelectList(_context.Set<Product>(), "Id", "Name");
            return View(variety);
        } 

        // GET: Varieties/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Variety == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety
                .Include(p => p.Products)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (variety == null)
            {
                return NotFound();
            }

            return View(variety);
        }

        // POST: Varieties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Variety == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Variety'  is null.");
            }
            var variety = await _context.Variety.FindAsync(id);
            variety.IsHidden = true;
            //if (variety != null)
            //{
            //    _context.Variety.Remove(variety);
            //}
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VarietyExists(int id)
        {
          return _context.Variety.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Bakers.Areas.Identity.Data;

@{
    string languageId = "nl";
    string cookieCulture = Context.Request.Cookies[CookieRequestCultureProvider.DefaultCookieName];
    if (cookieCulture != null)
    {
        languageId = cookieCulture.Substring(2, 2);
    }
    string languageName = Language.LanguagesDictionary[languageId].Name;

    //ophalen huidige pagina
    var thisPage = string.IsNullOrEmpty(Context.Request.Path) ? "~/index.html" : $"~{Context.Request.Path.Value}";
}

<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown" data-bs-toggle="dropdown">@languageName</a>
        <ul class="dropdown-menu">
            @foreach (Language l in Language.Languages)
                if (l.Id != languageId && l.IsShown)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area=""
                           asp-controller="Home"
                           asp-action="ChangeLanguage"
                           asp-route-id="@l.Id"
                           asp-route-returnUrl=@thisPage>
                            @l.Name
                        </a>
                    </li>
                }
        </ul>
    </li>
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bakers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bakers.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
        <nav class="navbar navbar-expand-md py-2 navbar-light" style="background-color: #C47C54;">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: white; font-size: 40px" asp-area="" asp-controller="Home" asp-action="Index">Baker's</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color: white;" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="color: white;" asp-area="" asp-controller="Varieties" asp-action="Index">Varieties</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                        <li class="nav-item">
                                <a class="nav-link" style="color: white;" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="color: white;" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        }
                        @if (User.IsInRole("admin") || User.IsInRole("employee"))
                        {
                        <li class="nav-item">
                            <a class="nav-link" style="color: white;" asp-area="" asp-controller="Suggestions" asp-action="Index">Suggestions</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" style="color: white;" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" style="color: white;" asp-area="" asp-controller="Orders" asp-action="MyOrders">My Orders</a>
                        </li>
                    @*<partial name="_LanguagePartial" />*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bakers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PieCard.cshtml
@model IEnumerable<Bakers.Models.Product>

<div class="col">
    <div class="card pie-card">
        <img src="https://images-gmi-pmc.edge-generalmills.com/173da066-c6b4-45dd-9b28-0d459cf6f169.jpg" class="card-img-top">
        <div class="card-body pie-button">
            <h4 class="d-grid">
                <a class="btn btn-secondary">Add to cart</a>
            </h4>

            <div class="d-flex justify-content-between mt-2">
                <h2 class="text-start">
                    <a class="pie-link">Chocolate Pie</a>
                </h2>
                <h5 class="text-nowrap">
                    22.99 €
                </h5>
            </div>
        </div>
    </div>
</div>